checks:shellcheck:
  stage: checks
  tags:
    - docker
  script:
    - shellcheck -x -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(sudo git ls-files))

checks:pylint:
  stage: checks
  tags:
    - docker
  before_script:
    - sudo dnf install python3-gobject gtk3
  script:
    - pylint-3 $(find ./ -type f -name '*.py')

include:
- file: /r4.1/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-dom0.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-vm-fedora.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-vm-debian.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
